// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlitedb

import (
	"database/sql"
	"time"
)

type ExternalIdentity struct {
	ID             string       `json:"id"`
	UserID         string       `json:"user_id"`
	Provider       string       `json:"provider"`
	ProviderUserID string       `json:"provider_user_id"`
	CreatedAt      time.Time    `json:"created_at"`
	UpdatedAt      time.Time    `json:"updated_at"`
	DeletedAt      sql.NullTime `json:"deleted_at"`
}

type ServiceAccount struct {
	ID         string       `json:"id"`
	Name       string       `json:"name"`
	Scopes     string       `json:"scopes"`
	CreatedAt  time.Time    `json:"created_at"`
	UpdatedAt  time.Time    `json:"updated_at"`
	DisabledAt sql.NullTime `json:"disabled_at"`
}

type ServiceAccountCredential struct {
	ID               string       `json:"id"`
	ServiceAccountID string       `json:"service_account_id"`
	SecretHash       string       `json:"secret_hash"`
	CreatedAt        time.Time    `json:"created_at"`
	ExpiresAt        sql.NullTime `json:"expires_at"`
	RevokedAt        sql.NullTime `json:"revoked_at"`
}

type SystemState struct {
	Key       string    `json:"key"`
	Value     string    `json:"value"`
	UpdatedAt time.Time `json:"updated_at"`
}

type User struct {
	ID             string         `json:"id"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
	DeletedAt      sql.NullTime   `json:"deleted_at"`
	Email          string         `json:"email"`
	HashedPassword sql.NullString `json:"hashed_password"`
	Hash           sql.NullString `json:"hash"`
	LastLoginAt    sql.NullTime   `json:"last_login_at"`
}
