// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlitedb

import (
	"database/sql"
	"time"
)

type ExternalIdentity struct {
	ID             string       `json:"id"`
	UserID         string       `json:"user_id"`
	Provider       string       `json:"provider"`
	ProviderUserID string       `json:"provider_user_id"`
	CreatedAt      time.Time    `json:"created_at"`
	UpdatedAt      time.Time    `json:"updated_at"`
	DeletedAt      sql.NullTime `json:"deleted_at"`
}

type User struct {
	ID             string         `json:"id"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
	DeletedAt      sql.NullTime   `json:"deleted_at"`
	Email          string         `json:"email"`
	HashedPassword sql.NullString `json:"hashed_password"`
	Hash           sql.NullString `json:"hash"`
	LastLoginAt    sql.NullTime   `json:"last_login_at"`
}
