// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlitedb

import (
	"context"
	"database/sql"
	"time"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*)
FROM users
WHERE deleted_at IS NULL
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createExternalIdentity = `-- name: CreateExternalIdentity :exec
INSERT INTO external_identities (
    id,
    user_id,
    provider,
    provider_user_id,
    created_at,
    updated_at
) VALUES (?, ?, ?, ?, ?, ?)
`

type CreateExternalIdentityParams struct {
	ID             string    `json:"id"`
	UserID         string    `json:"user_id"`
	Provider       string    `json:"provider"`
	ProviderUserID string    `json:"provider_user_id"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

func (q *Queries) CreateExternalIdentity(ctx context.Context, arg CreateExternalIdentityParams) error {
	_, err := q.db.ExecContext(ctx, createExternalIdentity,
		arg.ID,
		arg.UserID,
		arg.Provider,
		arg.ProviderUserID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (
    id,
    created_at,
    updated_at,
    email,
    hashed_password,
    hash,
    last_login_at
) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateUserParams struct {
	ID             string         `json:"id"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
	Email          string         `json:"email"`
	HashedPassword sql.NullString `json:"hashed_password"`
	Hash           sql.NullString `json:"hash"`
	LastLoginAt    sql.NullTime   `json:"last_login_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Email,
		arg.HashedPassword,
		arg.Hash,
		arg.LastLoginAt,
	)
	return err
}

const getExternalIdentityByProviderID = `-- name: GetExternalIdentityByProviderID :one
SELECT id, user_id, provider, provider_user_id, created_at, updated_at, deleted_at
FROM external_identities
WHERE provider = ? AND provider_user_id = ? AND deleted_at IS NULL
LIMIT 1
`

type GetExternalIdentityByProviderIDParams struct {
	Provider       string `json:"provider"`
	ProviderUserID string `json:"provider_user_id"`
}

func (q *Queries) GetExternalIdentityByProviderID(ctx context.Context, arg GetExternalIdentityByProviderIDParams) (ExternalIdentity, error) {
	row := q.db.QueryRowContext(ctx, getExternalIdentityByProviderID, arg.Provider, arg.ProviderUserID)
	var i ExternalIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, created_at, updated_at, deleted_at, email, hashed_password, hash, last_login_at
FROM users
WHERE email = ? AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Email,
		&i.HashedPassword,
		&i.Hash,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, created_at, updated_at, deleted_at, email, hashed_password, hash, last_login_at
FROM users
WHERE id = ? AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Email,
		&i.HashedPassword,
		&i.Hash,
		&i.LastLoginAt,
	)
	return i, err
}

const listExternalIdentitiesByUserID = `-- name: ListExternalIdentitiesByUserID :many
SELECT id, user_id, provider, provider_user_id, created_at, updated_at, deleted_at
FROM external_identities
WHERE user_id = ? AND deleted_at IS NULL
ORDER BY created_at ASC
`

func (q *Queries) ListExternalIdentitiesByUserID(ctx context.Context, userID string) ([]ExternalIdentity, error) {
	rows, err := q.db.QueryContext(ctx, listExternalIdentitiesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExternalIdentity{}
	for rows.Next() {
		var i ExternalIdentity
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.ProviderUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, created_at, updated_at, deleted_at, email, hashed_password, hash, last_login_at
FROM users
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT ?2 OFFSET ?1
`

type ListUsersParams struct {
	PageOffset int64 `json:"page_offset"`
	PageSize   int64 `json:"page_size"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Email,
			&i.HashedPassword,
			&i.Hash,
			&i.LastLoginAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteUser = `-- name: SoftDeleteUser :execrows
UPDATE users
SET deleted_at = ?, updated_at = ?
WHERE id = ? AND deleted_at IS NULL
`

type SoftDeleteUserParams struct {
	DeletedAt sql.NullTime `json:"deleted_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	ID        string       `json:"id"`
}

func (q *Queries) SoftDeleteUser(ctx context.Context, arg SoftDeleteUserParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, softDeleteUser, arg.DeletedAt, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateUser = `-- name: UpdateUser :execrows
UPDATE users
SET email = ?,
    hashed_password = ?,
    hash = ?,
    last_login_at = ?,
    updated_at = ?
WHERE id = ? AND deleted_at IS NULL
`

type UpdateUserParams struct {
	Email          string         `json:"email"`
	HashedPassword sql.NullString `json:"hashed_password"`
	Hash           sql.NullString `json:"hash"`
	LastLoginAt    sql.NullTime   `json:"last_login_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
	ID             string         `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateUser,
		arg.Email,
		arg.HashedPassword,
		arg.Hash,
		arg.LastLoginAt,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
