// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlitedb

import (
	"context"
)

type Querier interface {
	CountUsers(ctx context.Context) (int64, error)
	CreateExternalIdentity(ctx context.Context, arg CreateExternalIdentityParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	GetExternalIdentityByProviderID(ctx context.Context, arg GetExternalIdentityByProviderIDParams) (ExternalIdentity, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	ListExternalIdentitiesByUserID(ctx context.Context, userID string) ([]ExternalIdentity, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	SoftDeleteUser(ctx context.Context, arg SoftDeleteUserParams) (int64, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
